### ISSUE TITLE
Cant clone properly due Git LFS data quota.

### ISSUE THREAD

**Issue by re-tundra** [Kunal-Attri/Fruit-Quality-Detection#2]
> Downloading Android Files Java/FQD.zip (114 MB) Error downloading object: Android Files Java/FQD.zip (2a3cf4c): Smudge error: Error downloading Android Files Java/FQD.zip (2a3cf4c3fb928eae897fc412e35f4e7ce741cd4f1b0de8e2f57a93e76522d2db): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by Kunal-Attri** [comment]
Resolved
